-- MySQL Script generated by MySQL Workbench
-- Sat Jan 25 17:31:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `idprofesor` VARCHAR(15) NOT NULL COMMENT 'Este id corresponde al correo electronico institucional del estudiante sin el \"@unal.edu.co\" aprovechando que es unico por cada profesor.',
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idprofesor`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `idestudiante` VARCHAR(15) NOT NULL COMMENT 'Este id corresponde al correo electronico institucional del estudiante sin el \"@unal.edu.co\" aprovechando que es unico por cada estudiante.',
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idestudiante`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso_periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso_periodo` (
  `idcurso_periodo` INT NOT NULL AUTO_INCREMENT,
  `id_curso` INT NOT NULL,
  `year` YEAR NOT NULL,
  `trimestre` INT NOT NULL COMMENT 'Se usa con el mismo formato que se usa en la plataforma de Moodle: 2024 (Campo llenado en year, y 1 para indicar el primer semestre o 3 para indicar el segundo semestre)',
  PRIMARY KEY (`idcurso_periodo`),
  INDEX `idcurso_idx` (`id_curso` ASC) INVISIBLE,
  UNIQUE INDEX `curso_unico_periodo` (`id_curso` ASC, `year` ASC, `trimestre` ASC) VISIBLE,
  CONSTRAINT `idcurso`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `id_curso_periodo` INT NOT NULL,
  `profesor_encargado` VARCHAR(15) NOT NULL,
  `numero_de_grupo` INT NOT NULL,
  PRIMARY KEY (`idgrupo`),
  INDEX `id_curso_periodo_idx` (`id_curso_periodo` ASC) VISIBLE,
  INDEX `idprofesor_idx` (`profesor_encargado` ASC) VISIBLE,
  UNIQUE INDEX `unico_grupo` (`id_curso_periodo` ASC, `numero_de_grupo` ASC) VISIBLE,
  CONSTRAINT `idcurso_periodo`
    FOREIGN KEY (`id_curso_periodo`)
    REFERENCES `mydb`.`curso_periodo` (`idcurso_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idprofesor`
    FOREIGN KEY (`profesor_encargado`)
    REFERENCES `mydb`.`profesor` (`idprofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscrito` (
  `idinscrito` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` VARCHAR(15) NOT NULL,
  `id_grupo` INT NOT NULL,
  `nota_obtenida` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idinscrito`),
  INDEX `idgrupo_idx` (`id_grupo` ASC) VISIBLE,
  INDEX `idestudiante_idx` (`id_estudiante` ASC) VISIBLE,
  CONSTRAINT `idgrupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idestudiante`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
